In [1]:
import numpy as np

Basics of Array

In [2]:
# 1D array
arr = np.array([1,2,3,6])
print(arr)

[1 2 3 6]


In [3]:
arr.shape

(4,)

In [4]:
# 2D array as float data type
arr2 = np.array([(1,2,3), (5,6,7)], dtype = float)
print(arr2)

[[1. 2. 3.]
 [5. 6. 7.]]


In [5]:
arr2.shape

(2, 3)

In [6]:
# array of zeros
zero = np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
# array of particular value
a = np.full((3,4), 5)
print(a)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [8]:
# array of evenly spaced values
b = np.linspace(10,30,5)
print(b)

[10. 15. 20. 25. 30.]


In [9]:
# array of evenly spaced values specifying a step value
c = np.arange(10,30,5)
print(c)

[10 15 20 25]


Analyzing the Array

In [10]:
array = np.random.randint(10,90, (5,5))
print(array)

[[43 36 22 57 27]
 [65 21 71 74 25]
 [86 64 61 45 17]
 [76 42 75 42 27]
 [66 89 66 67 26]]


In [11]:
array.shape

(5, 5)

In [12]:
array.ndim

2

In [13]:
array.size

25

Array Manipulation

In [14]:
array, array.shape

(array([[43, 36, 22, 57, 27],
        [65, 21, 71, 74, 25],
        [86, 64, 61, 45, 17],
        [76, 42, 75, 42, 27],
        [66, 89, 66, 67, 26]]),
 (5, 5))

In [15]:
# trasnpose of an array
trans = np.transpose(array)
trans

array([[43, 65, 86, 76, 66],
       [36, 21, 64, 42, 89],
       [22, 71, 61, 75, 66],
       [57, 74, 45, 42, 67],
       [27, 25, 17, 27, 26]])

In [16]:
# reshaping an array
reshaped = array.reshape(1,25)
reshaped

array([[43, 36, 22, 57, 27, 65, 21, 71, 74, 25, 86, 64, 61, 45, 17, 76,
        42, 75, 42, 27, 66, 89, 66, 67, 26]])