### Numpy


In [1]:
import numpy as np

In [2]:
# create a numpy array
l = [1,2,3]
np.array(l)


array([1, 2, 3])

In [15]:
np.zeros(10)
a = np.zeros(10, int)

# multidimensional array
b = np.zeros((2,3,2))
a,b

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([[[0., 0.],
         [0., 0.],
         [0., 0.]],
 
        [[0., 0.],
         [0., 0.],
         [0., 0.]]]))

In [14]:
b.shape

(2, 3, 2)

In [18]:
c = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])
c[:,2:4]

array([[3],
       [6],
       [3],
       [6]])

#### Numpy Operations

In [25]:
a = np.array([1,2,3])
b = np.array([5,6,7])

print(a+2)
print(a+b)
print(a*b)
print(a**2)


[3 4 5]
[ 6  8 10]
[ 5 12 21]
[1 4 9]


In [26]:
a.sum()

6

In [27]:
 a.mean()

2.0

In [28]:
# sigma(x-x_mean)^2
((a - a.mean())**2).sum()

2.0

In [29]:
a1 = np.array([0, 1, 2, 3])
a2 = np.array([2, 3, 4, 5])
a1.dot(a2)

26

In [22]:
np.sum([[0, 1], [0, 5]], axis=1)


array([1, 5])