In [31]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression

In [32]:
df = pd.read_csv("training_titanic_x_y_train.csv")

In [33]:

df.head()

Pclass                                            Name     Sex   Age  \
0       2   Weisz, Mrs. Leopold (Mathilde Francoise Pede)  female  29.0   
1       3               Williams, Mr. Howard Hugh "Harry"    male   NaN   
2       2  Morley, Mr. Henry Samuel ("Mr Henry Marshall")    male  39.0   
3       3     Palsson, Mrs. Nils (Alma Cornelia Berglund)  female  29.0   
4       3                          Sutehall, Mr. Henry Jr    male  25.0   

   SibSp  Parch           Ticket    Fare Cabin Embarked  Survived  
0      1      0           228414  26.000   NaN        S         1  
1      0      0         A/5 2466   8.050   NaN        S         0  
2      0      0           250655  26.000   NaN        S         0  
3      0      4           349909  21.075   NaN        S         0  
4      0      0  SOTON/OQ 392076   7.050   NaN        S         0

In [34]:
df.drop(["Name","Ticket"],axis=1,inplace=True)

In [35]:
def gender(g):
    if g == "male":
        return 1
    else:
        return 0
df["Gender"] = df["Sex"].apply(gender)
df.head()

Pclass     Sex   Age  SibSp  Parch    Fare Cabin Embarked  Survived  Gender
0       2  female  29.0      1      0  26.000   NaN        S         1       0
1       3    male   NaN      0      0   8.050   NaN        S         0       1
2       2    male  39.0      0      0  26.000   NaN        S         0       1
3       3  female  29.0      0      4  21.075   NaN        S         0       0
4       3    male  25.0      0      0   7.050   NaN        S         0       1

In [36]:
df.drop(['Sex'], axis = 1, inplace =True)
df.head()

Pclass   Age  SibSp  Parch    Fare Cabin Embarked  Survived  Gender
0       2  29.0      1      0  26.000   NaN        S         1       0
1       3   NaN      0      0   8.050   NaN        S         0       1
2       2  39.0      0      0  26.000   NaN        S         0       1
3       3  29.0      0      4  21.075   NaN        S         0       0
4       3  25.0      0      0   7.050   NaN        S         0       1

In [37]:
df.isnull().sum()

Pclass        0
Age         132
SibSp         0
Parch         0
Fare          0
Cabin       514
Embarked      1
Survived      0
Gender        0
dtype: int64

In [38]:
def cabin(x):
    if x is np.nan:
        return 0
    else:
        return 1
df["Cabin"] = df.Cabin.apply(cabin)
df.head()

Pclass   Age  SibSp  Parch    Fare  Cabin Embarked  Survived  Gender
0       2  29.0      1      0  26.000      0        S         1       0
1       3   NaN      0      0   8.050      0        S         0       1
2       2  39.0      0      0  26.000      0        S         0       1
3       3  29.0      0      4  21.075      0        S         0       0
4       3  25.0      0      0   7.050      0        S         0       1

In [39]:
df.isnull().sum()

Pclass        0
Age         132
SibSp         0
Parch         0
Fare          0
Cabin         0
Embarked      1
Survived      0
Gender        0
dtype: int64

In [40]:
# Fill mean Survived age in the column where the person has survived and 
# mean not Survived age in the column where person has not survived

mean_age_sur = df[df.Survived == 1].Age.mean()
mean_age_not_sur = df[df.Survived == 0].Age.mean()

df.Age.fillna(mean_age_sur, inplace = True)
df.Age.fillna(mean_age_not_sur, inplace = True)
df.head()

Pclass        Age  SibSp  Parch    Fare  Cabin Embarked  Survived  Gender
0       2  29.000000      1      0  26.000      0        S         1       0
1       3  28.138158      0      0   8.050      0        S         0       1
2       2  39.000000      0      0  26.000      0        S         0       1
3       3  29.000000      0      4  21.075      0        S         0       0
4       3  25.000000      0      0   7.050      0        S         0       1

In [41]:
df.isnull().sum()

Pclass      0
Age         0
SibSp       0
Parch       0
Fare        0
Cabin       0
Embarked    1
Survived    0
Gender      0
dtype: int64

In [42]:
def cherbourg(s):
    if s=="C":
        return 1
    else:
        return 0
    
def queenstown(s):
    if s=="Q":
        return 1
    else:
        return 0

def southamptom(s):
    if s=="S":
        return 1
    else:
        return 0
        
df["Cherbourg"] = df.Embarked.apply(cherbourg)
df["Queenstown"] = df.Embarked.apply(queenstown)
df["Southamptom"] = df.Embarked.apply(southamptom)
df.drop("Embarked",axis=1, inplace=True)
df.head()

Pclass        Age  SibSp  Parch    Fare  Cabin  Survived  Gender  \
0       2  29.000000      1      0  26.000      0         1       0   
1       3  28.138158      0      0   8.050      0         0       1   
2       2  39.000000      0      0  26.000      0         0       1   
3       3  29.000000      0      4  21.075      0         0       0   
4       3  25.000000      0      0   7.050      0         0       1   

   Cherbourg  Queenstown  Southamptom  
0          0           0            1  
1          0           0            1  
2          0           0            1  
3          0           0            1  
4          0           0            1

In [43]:
df.isnull().sum()

Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Cabin          0
Survived       0
Gender         0
Cherbourg      0
Queenstown     0
Southamptom    0
dtype: int64

In [46]:
df = df[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare','Cabin','Gender','Cherbourg','Queenstown','Southamptom','Survived']]
df.head()

Pclass        Age  SibSp  Parch    Fare  Cabin  Gender  Cherbourg  \
0       2  29.000000      1      0  26.000      0       0          0   
1       3  28.138158      0      0   8.050      0       1          0   
2       2  39.000000      0      0  26.000      0       1          0   
3       3  29.000000      0      4  21.075      0       0          0   
4       3  25.000000      0      0   7.050      0       1          0   

   Queenstown  Southamptom  Survived  
0           0            1         1  
1           0            1         0  
2           0            1         0  
3           0            1         0  
4           0            1         0

In [47]:
data = df.values
data

array([[ 2.        , 29.        ,  1.        , ...,  0.        ,
         1.        ,  1.        ],
       [ 3.        , 28.13815789,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 2.        , 39.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [ 3.        , 32.        ,  0.        , ...,  0.        ,
         1.        ,  1.        ],
       [ 3.        , 22.        ,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 3.        , 28.13815789,  1.        , ...,  1.        ,
         0.        ,  1.        ]])

In [48]:
data.shape

(668, 11)

In [49]:
X = data[:, 0:10]
Y = data[:, 10]
X.shape,Y.shape

((668, 10), (668,))

In [61]:
clf = LogisticRegression(max_iter=1000)

In [62]:
clf.fit(X, Y)

LogisticRegression(max_iter=1000)

In [63]:
clf.score(X, Y)

0.7934131736526946

In [64]:
clf.predict_proba(X)

array([[0.25232195, 0.74767805],
       [0.8830512 , 0.1169488 ],
       [0.82674362, 0.17325638],
       ...,
       [0.89612066, 0.10387934],
       [0.31622119, 0.68377881],
       [0.36243581, 0.63756419]])

In [65]:
clf.predict(X) - Y

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0., -1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
        0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0., -1.,
        0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0., -1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  1., -1.,
        1.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -1.,  0.,  1.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  1., -1.,  1.,  0., -1.,  0.,  0.,  1.,  0.,  0.,
        0.,  0., -1.,  0.,  0.,  0.,  0., -1., -1.,  0.,  0.,  0

In [66]:
test = pd.read_csv("test_titanic_x_test.csv")    
test.head()

Pclass                                               Name     Sex   Age  \
0       2                     Davies, Master. John Morgan Jr    male   8.0   
1       1                        Leader, Dr. Alice (Farnham)  female  49.0   
2       3                            Kilgannon, Mr. Thomas J    male   NaN   
3       2  Jacobsohn, Mrs. Sidney Samuel (Amy Frances Chr...  female  24.0   
4       1                          McGough, Mr. James Robert    male  36.0   

   SibSp  Parch      Ticket     Fare Cabin Embarked  
0      1      1  C.A. 33112  36.7500   NaN        S  
1      0      0       17465  25.9292   D17        S  
2      0      0       36865   7.7375   NaN        Q  
3      2      1      243847  27.0000   NaN        S  
4      0      0    PC 17473  26.2875   E25        S

In [67]:
test.isnull().sum()

Pclass        0
Name          0
Sex           0
Age          45
SibSp         0
Parch         0
Ticket        0
Fare          0
Cabin       173
Embarked      1
dtype: int64

In [69]:
test.drop(["Name","Ticket"],axis=1,inplace=True)

test["Gender"] = test["Sex"].apply(gender)
test.drop(['Sex'], axis = 1, inplace =True)

test["Cabin"] = test.Cabin.apply(cabin)

test.Age.fillna(test["Age"].mean(), inplace = True)

test["Cherbourg"] = test.Embarked.apply(cherbourg)
test["Queenstown"] = test.Embarked.apply(queenstown)
test["Southamptom"] = test.Embarked.apply(southamptom)
test.drop("Embarked",axis=1, inplace=True)

df.isnull().sum()

Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Cabin          0
Gender         0
Cherbourg      0
Queenstown     0
Southamptom    0
Survived       0
dtype: int64

In [71]:
test = test[['Pclass', 'Age', 'SibSp', 'Parch', 'Fare','Cabin','Gender','Cherbourg','Queenstown','Southamptom']]
test.head()

Pclass        Age  SibSp  Parch     Fare  Cabin  Gender  Cherbourg  \
0       2   8.000000      1      1  36.7500      0       1          0   
1       1  49.000000      0      0  25.9292      1       0          0   
2       3  29.694775      0      0   7.7375      0       1          0   
3       2  24.000000      2      1  27.0000      0       0          0   
4       1  36.000000      0      0  26.2875      1       1          0   

   Queenstown  Southamptom  
0           0            1  
1           0            1  
2           1            0  
3           0            1  
4           0            1

In [72]:
test = test.values

In [73]:
y_pred_test = clf.predict(test)

In [74]:
y_pred_test

array([0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0.,
       0., 0., 1., 1., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 0., 0., 0., 0., 1.,
       0., 0.])

In [75]:
np.savetxt("survived.csv", y_pred_test)

In [76]:
df.isnull().sum()

Pclass         0
Age            0
SibSp          0
Parch          0
Fare           0
Cabin          0
Gender         0
Cherbourg      0
Queenstown     0
Southamptom    0
Survived       0
dtype: int64