In [1]:
import numpy as np

In [3]:
X = np.array([[0,0], [1,0], [1,0], [1,1]])
Y = np.array([[0, 0, 0, 1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [4]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [16]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

#### Forward Propagation with no hidden layers 

In [9]:
weights = 2* np.random.random((2,1)) -1 # range is -1 to 1
bias = np.random.random(1) -1
weights, bias

(array([[0.76740685],
        [0.75028859]]),
 array([-0.41154291]))

In [12]:
# forward propagation with no hidden layers weights
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.39854222],
       [0.58803884],
       [0.58803884],
       [0.75141113]])

#### Forward Propagation with one hidden layer

In [13]:
wh = 2* np.random.random((2,2)) -1 # range is -1 to 1 ; shape = (no. of features, no. of units in hidden layer)
bh = np.random.random((1,2)) -1
wo = np.random.random((2,1)) -1 # output weights
bo = np.random.random((1,1)) -1 # output bias

In [15]:
# forward propagation with no hidden layers weights
output0 = X
output_hidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(output_hidden, wo) + bo)

output

array([[0.25253429],
       [0.24783822],
       [0.24783822],
       [0.25534293]])