In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [1,0], [1,0], [1,1]])
Y = np.array([[0, 0, 0, 1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

In [23]:
weights = 2* np.random.random((2,1)) -1 # range is -1 to 1
bias = np.random.random(1) -1
lr = 0.1
weights, bias

(array([[ 0.95131138],
        [-0.70718465]]),
 array([-0.93536288]))

In [21]:
# forward propagation with no hidden layers weights
for iter in range(10000):
    
    output0 = X
    output = sig(np.dot(output0, weights) + bias)
    
    first_term = output-Y
    input_for_last_layer = sig(np.dot(output0, weights) + bias)
    second_term = derivativeSig(input_for_last_layer)
    
    first_two = first_term * second_term
    first_two.shape
    
    changes = np.array([[0.0], [0.0]])
    for i in range(2):
        for j in range(4):
            changes[i][0] += first_two[j][0] * output0[j][0]
            
    weights = weights - lr*changes
    
    bias_change = 0.0
    for j in range(4):
            bias_change += first_two[j][0] * 1
    bias = bias - lr*bias_change
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[3.41954169],
        [3.52551594]]),
 array([-5.68029074]),
 array([[0.00340096],
        [0.0944263 ],
        [0.0944263 ],
        [0.77984561]]))

In [25]:
# optimized code using vector operations
for iter in range(10000):
    
    output0 = X
    output = sig(np.dot(output0, weights) + bias)
    first_term = output-Y
    input_for_last_layer = sig(np.dot(output0, weights) + bias)
    second_term = derivativeSig(input_for_last_layer)
    
    first_two = first_term * second_term
    first_two.shape
    
    changes = np.dot(output0.T, first_two)
    weights = weights - lr*changes
    
    bias_change = np.sum(first_two)
    bias = bias - lr*bias_change
    
output = sig(np.dot(X, weights) + bias)
weights, bias, output

(array([[ 0.12315388],
        [11.43319548]]),
 array([-6.29467392]),
 array([[0.00184271],
        [0.00208371],
        [0.00208371],
        [0.99484015]]))