In [1]:
import numpy as np

In [12]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0, 1, 1, 0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [4]:
def derivativeSig(z):
    return sig(z) * (1-sig(z))

In [14]:
wh = 2* np.random.random((2,2)) -1 # range is -1 to 1 ; shape = (no. of features, no. of units in hidden layer)
bh = np.random.random((1,2)) -1
wo = np.random.random((2,1)) -1 # output weights
bo = np.random.random((1,1)) -1 # output bias

lr = 0.1

In [15]:
# forward propagation with one hidden layers weights
for iter in range(100000):
    output0 = X
    input_hidden = np.dot(output0, wh) + bh
    output_hidden = sig(input_hidden)
    
    input_for_output_layer = np.dot(output_hidden, wo) + bo
    output = sig(input_for_output_layer)
    
    first_term_output_layer = output-Y
    second_term_output_layer = derivativeSig(input_for_output_layer)
    first_two_output_layer = first_term_output_layer * second_term_output_layer
    
    first_term_hidden_layer = np.dot(first_two_output_layer, wo.T)
    second_term_hidden_layer = derivativeSig(input_hidden)
    first_two_hidden_layer = first_term_hidden_layer * second_term_hidden_layer
    
    changes_output = np.dot(output_hidden.T, first_two_output_layer)
    changes_output_bias = np.sum(first_two_output_layer, axis = 0, keepdims = True)
    
    changes_hidden = np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias = np.sum(first_two_hidden_layer, axis = 0, keepdims = True)
    
    wo = wo - lr*changes_output
    bo = bo - lr*changes_output_bias
    
    wh = wh - lr*changes_hidden
    bh = bh - lr*changes_hidden_bias

output0 = X
input_hidden = np.dot(output0, wh) + bh
output_hidden = sig(input_hidden)

input_for_output_layer = np.dot(output_hidden, wo) + bo
output = sig(input_for_output_layer)

output, wh, bh, wo, bo

(array([[0.01068265],
        [0.98882329],
        [0.98880964],
        [0.01376164]]),
 array([[-5.03319742, -6.66232872],
        [-5.03715865, -6.68282144]]),
 array([[7.50519564, 2.76890357]]),
 array([[ 10.53928337],
        [-10.66714113]]),
 array([[-5.02439934]]))